name: Build and deploy documentation

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install pip dependencies
        run: pip install sphinx==6.1.3 sphinx-rtd-theme==1.2.2 myst-parser==1.0.0

      - name: Compile static HTML
        run: sphinx-build -b html docs/source docs/_build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/_build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
