name: Release

on:
  release:
    types: [published]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  release-test:
    name: Release
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Bump version
        run:
          poetry version ${{ github.event.release.tag_name }}
          git add pyproject.toml
          git commit -m "bump version to ${{ github.event.release.tag_name }}"
          git push

      - uses: actions/checkout@v3
      - name: Build and publish to test pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          ignore_dev_requirements: "yes"
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"

      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          ignore_dev_requirements: "yes"
