name: Release

on:
  release:
    types: [created]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  release-test:
    name: Test Release
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          ignore_dev_requirements: "yes"
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"

  release:
    name: Release
    needs: [release-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          ignore_dev_requirements: "yes"
