name: Release

on:
  release:
    types: [published]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  release:
    name: Release
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check version
        run: grep '^version = "${{ github.event.release.tag_name }}"' pyproject.toml

      - uses: actions/checkout@v3
      - name: Build and publish to test pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          ignore_dev_requirements: "yes"
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"

      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          ignore_dev_requirements: "yes"
