name: Tests

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  integration-tests:
    name: Integration tests ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [ Ubuntu ]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        include:
          - os: Ubuntu
            image: ubuntu-22.04
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build tests image
        run: docker compose -f .ci/docker-compose.yml build --build-arg PYTHON_VERSION=${{ matrix.python-version }}

      - name: Run integration tests
        run: docker compose -f .ci/docker-compose.yml run xtdb_py_integration

  unit-tests:
    name: Unit tests ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [ Ubuntu, macOS, Windows ]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        include:
          - os: Ubuntu
            image: ubuntu-22.04
          - os: Windows
            image: windows-2022
          - os: macOS
            image: macos-12
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install requirements
        run: poetry install --with dev

      - name: Run unit tests
        run: poetry run pytest

  checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        id: py38
        with:
          python-version: 3.8
          cache: pip

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Checks
        run: pre-commit run --all --show-diff-on-failure --color always
